catalog = [
    {
      "title": "Tomatoes",
      "price": 7.68,
      "category": "vegetable",
      "image": "tom1.jpg",
      "_id": "1",
    },
    {
      "title": "Oranges",
      "price": 2.98,
      "category": "fruit",
      "image": "organges.jpg",
      "_id": "2",
    },
    {
      "title": "Apples",
      "price": 1.99,
      "category": "fruit",
      "image": "apples.jpg",
      "_id": "3",
    },
    {
      "title": "Eggs",
      "price": 6.99,
      "category": "eggs",
      "image": "eggs.jpg",
      "_id": "4",
    },
    {
      "title": "fruit Juice",
      "price": 6.68,
      "category": "fruit",
      "image": "juice.jpg",
      "_id": "5",
    },
    {
      "title": "Deli meats",
      "price": 5.99,
      "category": "meat",
      "image": "deli.jpg",
      "_id": "6",
    },
    {
      "title": "Green Beans",
      "price": 6.98,
      "category": "vegetable",
      "image": "greenbeans.jpg",
      "_id": "7",
    },
    {
      "title": "Grapes",
      "price": 4.98,
      "category": "fruit",
      "image": "grapes.jpg",
      "_id": "8",
    },
    {
      "title": "Romaine Lettuce",
      "price": 8.98,
      "category": "vegetable",
      "image": "lettuce.jpg",
      "_id": "9",
    },
    {
      "title": "Chicken",
      "price": 8.98,
      "category": "meat",
      "image": "chicken1.jpg",
      "_id": "10",
    },
    {
      "title": "Nuts",
      "price": 4.98,
      "category": "nuts",
      "image": "nuts.jpg",
      "_id": "11",
    },
    {
      "title": "Coffee Beans",
      "price": 8.98,
      "category": "coffee",
      "image": "coffee5.jpg",
      "_id": "12",
    },
    {
      "title": "Fresh Milk",
      "price": 6.98,
      "category": "Dairy",
      "image": "milk1.jpg",
      "_id": "13",
    },
    {
      "title": "cheese",
      "price": 8.98,
      "category": "dairy",
      "image": "cheese.jpg",
      "_id": "14",
    },
    {
      "title": "yogurt",
      "price": 4.98,
      "category": "dairy",
      "image": "yogurt.jpg",
      "_id": "15",
    },
    {
      "title": "Pork",
      "price": 8.98,
      "category": "meats",
      "image": "pork.jpg",
      "_id": "16",
    },
    {
      "title": "Sausage",
      "price": 8.98,
      "category": "meats",
      "image": "sausage.jpg",
      "_id": "17",
    },
    {
      "title": "Steaks",
      "price": 28.98,
      "category": "meats",
      "image": "steaks.jpg",
      "_id": "18",
    },
    {
      "title": "Artichoke",
      "price": 3.98,
      "category": "vegetables",
      "image": "artichoke.jpg",
      "_id": "19",
    },
    {
      "title": "Honey",
      "price": 8.98,
      "category": "honey",
      "image": "honey.jpg",
      "_id": "20",
    },
  ]